linters-settings:
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
      - diagnostic
      - opinionated
    disabled-checks:
      - unnamedResult
      - hugeParam

linters:
  enable:
    - deadcode    # Finds unused code [fast: false, auto-fix: false]
    - errcheck    # Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases [fast: false, auto-fix: false]
    - gosimple    # (megacheck) Linter for Go source code that specializes in simplifying a code [fast: false, auto-fix: false]issues:
    - govet       # (vet, vetshadow) Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string [fast: false, auto-fix: false]  exclude-use-default: false
    - ineffassign # Detects when assignments to existing variables are not used [fast: true, auto-fix: false]  exclude-rules:
    - staticcheck # (megacheck) Staticcheck is a go vet on steroids, applying a ton of static analysis checks [fast: false, auto-fix: false]    # False positive error (package comment exists in adapter.go)
    - structcheck # Finds unused struct fields [fast: false, auto-fix: false]    - text: "should have a package comment, unless it's in another file for this package"
    - typecheck   # Like the front-end of a Go compiler, parses and type-checks Go code [fast: false, auto-fix: false]      linters:
    - unused      # Checks Go code for unused constants, variables, functions and types [fast: false, auto-fix: false]        - golint
    - varcheck    # Finds unused global variables and constants [fast: false, auto-fix: false]
    - bodyclose   # checks whether HTTP response body is closed successfully [fast: false, auto-fix: false]
    - gocritic    # Provides diagnostics that check for bugs, performance and style issues. [fast: false, auto-fix: false]
    - goimports   # In addition to fixing imports, goimports also formats your code in the same style as gofmt. [fast: true, auto-fix: true]
    - gosec       # (gas) Inspects source code for security problems [fast: false, auto-fix: false]
    - misspell    # Finds commonly misspelled English words in comments [fast: true, auto-fix: true]
    - makezero    # Finds slice declarations with non-zero initial length [fast: false, auto-fix: false]
    - stylecheck  # Stylecheck is a replacement for golint [fast: false, auto-fix: false]
    - lll         # Reports long lines [fast: true, auto-fix: false]
